INSERT INTO RESTAURANTS (NAME) VALUES ('Piggy''s Pizza Parlor');
INSERT INTO RESTAURANTS (NAME) VALUES ('Xanatos Zuppe');

INSERT INTO RESERVATIONS (RESTAURANT_ID, PARTY_SIZE) values (1, 2);
INSERT INTO RESERVATIONS (RESTAURANT_ID, PARTY_SIZE) values (1, 4);