INSERT INTO RESTAURANTS (NAME) VALUES ('Piggy''s Pizza Parlor');
INSERT INTO RESTAURANTS (NAME) VALUES ('Xanatos Zuppe');

INSERT INTO RESERVATIONS (RESTAURANT_ID, PARTY_SIZE, RESERVED_BY, RESERVATION_TIME, CANCELLED)
  VALUES (1, 2, 'John Smith', '2014-06-01 19:00:00', FALSE);

INSERT INTO RESERVATIONS (RESTAURANT_ID, PARTY_SIZE, RESERVED_BY, RESERVATION_TIME, CANCELLED)
  VALUES (1, 4, 'Janet Yi', '2014-06-01 19:00:00', FALSE);

INSERT INTO RESERVATIONS (RESTAURANT_ID, PARTY_SIZE, RESERVED_BY, CANCELLED) values (2, 2, 'Margaret Thompson', FALSE);
INSERT INTO RESERVATIONS (RESTAURANT_ID, PARTY_SIZE, RESERVED_BY, CANCELLED) values (2, 4, 'Cory Young', FALSE);
INSERT INTO RESERVATIONS (RESTAURANT_ID, PARTY_SIZE, RESERVED_BY, CANCELLED) values (2, 6, 'Fred Marker', FALSE);