//REMOVE THIS EVENTUALLY. USING JPA TO AUTO-GEN DB schema for this lab.

CREATE TABLE RESTAURANTS (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100)
);

CREATE TABLE RESERVATIONS (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	PARTY_SIZE INT,
	RESTAURANT_ID BIGINT);